### ISSUE TITLE
Broker accepts SUBSCRIBE with invalid topic

### ISSUE THREAD

**Issue by QuantumFlux2** [redboltz/async_mqtt#379]
While using the broker, I encountered that it accepted a `SUBSCRIBE` packet with an invalid topic name containing a Unicode null character (`U+0000`). The broker responded with a `SUBACK` instead of rejecting the packet or disconnecting the client.

According to the MQTT 5.0 specification, a topic name containing the null character should be treated as a Malformed Packet. In such cases, the expected behavior is for the broker to either reject the subscription and not send a `SUBACK`, or disconnect the client with an appropriate Reason Code.

Below is the hexadecimal representation of the `SUBSCRIBE` packet used:
`820a00350000047574663800`

![image](https://github.com/user-attachments/assets/5687bd98-db80-4ab7-ab8c-4a97ee4177d7)
I also found this problem in the publish scenario.
Below is the hexadecimal representation of the PUBLISH packet used:
`3211000c696e76616c69640075746638003500`

**Comment by redboltz** [comment]
Thank you for reporting the issue. It should be fixed by #381 . Could you try this ?

**Comment by QuantumFlux2** [comment]
Thank you for the update. I have tested the fix, and the issue with the PUBLISH packet has been resolved as expected. However, I am still receiving a SUBACK when subscribing with a topic name containing the Unicode null character.

**Comment by redboltz** [comment]
I noticed that your SUBSCRIBE packet is valid.

> While using the broker, I encountered that it accepted a `SUBSCRIBE` packet with an invalid topic name containing a Unicode null character (`U+0000`). The broker responded with a `SUBACK` instead of rejecting the packet or disconnecting the client.
> 
> According to the MQTT 5.0 specification, a topic name containing the null character should be treated as a Malformed Packet. In such cases, the expected behavior is for the broker to either reject the subscription and not send a `SUBACK`, or disconnect the client with an appropriate Reason Code.
> 
> Below is the hexadecimal representation of the `SUBSCRIBE` packet used: `820a00350000047574663800`

index|data|meaning
---|---|---
0|82|Fixed header for SUBSCRIBE
1|0a|Remaining Lengh 10 bytes
2|00|Packet Identifier(H)
3|35|Packet Identifier(L)
4|00|Property Length 0
5|00|Topic Filter Length(H) 4 bytes
6|04|Topic Filter Length(L)
7|75|Topic Filter String index 0
8|74|Topic Filter String  index 1
9|66|Topic Filter String  index 2
10|38|Topic Filter String  index 3 (total 4 bytes)
11|00|Subscribe Options QoS0 no flags

**Comment by QuantumFlux2** [comment]
Thank you for your correction. After retrying, I found that the issue had been resolved successfully. I appreciate your help!

**Comment by redboltz** [comment]
You are welcome! Thank you for your cooperation, it improoved async_mqtt.
